name: ${project.name}
main: net.civex4.nobility.Nobility
version: ${project.version}
depend: [NobilityRegions]
api-version: 1.13
commands:
   nobility:
      description: nobility
      usage: /nobility <argument> [other stuff]
      aliases: [ n ]
   test:
      description: Tests stuff
   create:
      description: Creates an estate at player's feet
      usage: /create or /c
      aliases: [ c ]
